// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBve1xECuy9IDHKRiv8--WZ08IU3_Vq8U8',
    appId: '1:1098083583047:web:11898f137dc42b1e815d62',
    messagingSenderId: '1098083583047',
    projectId: 'weatherman-c482a',
    authDomain: 'weatherman-c482a.firebaseapp.com',
    storageBucket: 'weatherman-c482a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZi4Wkp65_stoFlgfmNA5EGAsd0pNvgss',
    appId: '1:1098083583047:android:f238c407e0a89139815d62',
    messagingSenderId: '1098083583047',
    projectId: 'weatherman-c482a',
    storageBucket: 'weatherman-c482a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeEjCpOpYuTxyFbdNZfrYz1JsAQtc_pLM',
    appId: '1:1098083583047:ios:50d59201cb18f8ee815d62',
    messagingSenderId: '1098083583047',
    projectId: 'weatherman-c482a',
    storageBucket: 'weatherman-c482a.firebasestorage.app',
    iosBundleId: 'com.example.fieldview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeEjCpOpYuTxyFbdNZfrYz1JsAQtc_pLM',
    appId: '1:1098083583047:ios:50d59201cb18f8ee815d62',
    messagingSenderId: '1098083583047',
    projectId: 'weatherman-c482a',
    storageBucket: 'weatherman-c482a.firebasestorage.app',
    iosBundleId: 'com.example.fieldview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBve1xECuy9IDHKRiv8--WZ08IU3_Vq8U8',
    appId: '1:1098083583047:web:67521b582e7507da815d62',
    messagingSenderId: '1098083583047',
    projectId: 'weatherman-c482a',
    authDomain: 'weatherman-c482a.firebaseapp.com',
    storageBucket: 'weatherman-c482a.firebasestorage.app',
  );
}
